### ISSUE TITLE
Oryx Site has Changed

### ISSUE THREAD

**Issue by leedrake5** [scarnecchia/scrape_oryx#18]
Russia is still located here: https://www.oryxspioenkop.com/2022/02/attack-on-europe-documenting-equipment.html

But Ukraine is now listed here: https://www.oryxspioenkop.com/2022/02/attack-on-europe-documenting-ukrainian.html

The good news is that you no longer need to reference the T-64BV tank to find positions, bad news is a lot of functions need to be updated.

**Comment by scarnecchia** [comment]
Hi @leedrake5, I just finished making the changes and kicked the tires. I'm going to merge that PR to main and that will close this, but let me know if you find any bugs I missed.

**Comment by leedrake5** [comment]
One possible fix (and note, switching to argument defaults instead of hard links makes it compatible with the Wayback Machine for getting archival data):

    russia_materiel <-
      get_data(
        russia_link,
        "article"
      ) %>%
      rvest::html_elements("li")
      
      ukraine_materiel <-
        get_data(
        ukraine_link,
          "article"
        ) %>%
        rvest::html_elements("li")
        
        materiel <- c(russia_materiel, ukraine_materiel)

Note that this requires the 'do' package to concat xml node sets.

**Comment by leedrake5** [comment]
Oops, you beat me to it

**Comment by scarnecchia** [comment]
Hi @leedrake5 : I made a small change right before merging that lets you set the URLs in the master program. For pre-4/20 versions of the website, simply set both URLs to the same page.
